const express = require('express');
const adminController = require("../controllers/AdminController");
const jwtMiddleware = require('../middleware/JWTMiddleware');
const router = express.Router();
router.use(jwtMiddleware(["admin"]));
router.get("/user/all", adminController.getAllUsers.bind(adminController));
router.get("/user/statistic", adminController.getUserRegistrationStats.bind(adminController));
router.get("/user/count-all", adminController.countAllUsers.bind(adminController));
router.get("/model/all", adminController.getAllModels.bind(adminController));
router.get("/model/count-all", adminController.countAllModels.bind(adminController));
router.post("/model/create", adminController.createModel.bind(adminController));
router.put("/model/edit/:id", adminController.editModel.bind(adminController));
router.delete("/model/delete/:id", adminController.deleteModel.bind(adminController));
router.get("/gift-code/all", adminController.getAllGiftCodes.bind(adminController));
router.get("/gift-code/count-all", adminController.countAllGiftCodes.bind(adminController));
router.post("/gift-code/create", adminController.createGiftCode.bind(adminController));
router.patch("/gift-code/edit/:id", adminController.editGiftCode.bind(adminController));
router.delete("/gift-code/delete/:id", adminController.deleteGiftCode.bind(adminController));
router.get("/transaction/all", adminController.getAllPaymentTransactions.bind(adminController));
router.get("/transaction/count-all", adminController.countAllPaymentTransactions.bind(adminController));
router.get("/wallet/all", adminController.getAllWallets.bind(adminController));
router.get("/candidate/all", adminController.getAllCandidates.bind(adminController));
router.get("/company/all", adminController.getAllCompanies.bind(adminController));
router.get("/category/all", adminController.getAllCategories.bind(adminController));
router.get("/job/all", adminController.getAllJobs.bind(adminController));
router.get("/recruiter-companies/all", adminController.getAllRecruiterCompanies.bind(adminController));
router.get("/career-handbook/all", adminController.getAllCareerHandbooks.bind(adminController));
module.exports = router;
