const express = require('express');
const adminController = require("../controllers/AdminController");
const jwtMiddleware = require('../middleware/JWTMiddleware');
const router = express.Router();
router.use(jwtMiddleware(["admin"]));
router.get("/user/all", adminController.getAllUsers.bind(adminController));
router.get("/user/statistic", adminController.getUserRegistrationStats.bind(adminController));
router.get("/user/count-all", adminController.countAllUsers.bind(adminController));
router.get("/user/count-recruiter", adminController.countAllRecruiterUsers.bind(adminController));
router.get("/model/all", adminController.getAllModels.bind(adminController));
router.get("/model/count-all", adminController.countAllModels.bind(adminController));
router.post("/model/create", adminController.createModel.bind(adminController));
router.put("/model/edit/:id", adminController.editModel.bind(adminController));
router.delete("/model/delete/:id", adminController.deleteModel.bind(adminController));
router.get("/gift-code/all", adminController.getAllGiftCodes.bind(adminController));
router.get("/gift-code/count-all", adminController.countAllGiftCodes.bind(adminController));
router.post("/gift-code/create", adminController.createGiftCode.bind(adminController));
router.patch("/gift-code/edit/:id", adminController.editGiftCode.bind(adminController));
router.delete("/gift-code/delete/:id", adminController.deleteGiftCode.bind(adminController));
router.get("/transaction/all", adminController.getAllPaymentTransactions.bind(adminController));
router.get("/transaction/count-all", adminController.countAllPaymentTransactions.bind(adminController));
router.get("/wallet/all", adminController.getAllWallets.bind(adminController));
router.get("/candidate/all", adminController.getAllCandidates.bind(adminController));
router.get("/company/all", adminController.getAllCompanies.bind(adminController));
router.get("/category/all", adminController.getAllCategories.bind(adminController));
router.get("/job/all", adminController.getAllJobs.bind(adminController));
router.get("/recruiter-companies/all", adminController.getAllRecruiterCompanies.bind(adminController));
router.get("/career-handbook/all", adminController.getAllCareerHandbooks.bind(adminController));
router.patch("/recruiter-companies/update-status/:recruiter_id", adminController.updateStatusRecruiterCompany.bind(adminController));
router.get("/job/count-all", adminController.countAllJobs.bind(adminController));
router.put('/jobs/:id', adminController.editJob.bind(adminController));
router.get("/company/detail/:id", adminController.getCompanyDetailByCompanyId.bind(adminController));
router.get("/user/detail/:id", adminController.getUserDetail.bind(adminController));
router.get("/reviews/all", adminController.getAllReviews.bind(adminController));
router.get("/reviews/company/:company_id", adminController.getAllReviewsByCompanyId.bind(adminController));
router.post("/category/create", adminController.createCategory.bind(adminController));
router.patch("/category/edit/:category_id", adminController.editCategory.bind(adminController));
router.delete("/category/delete/:category_id", adminController.deleteCategory.bind(adminController));
router.post("/career-handbook/create", adminController.createCareerHandbook.bind(adminController));
router.patch("/career-handbook/edit/:post_id", adminController.editCareerHandbook.bind(adminController));
router.delete("/career-handbook/delete/:post_id", adminController.deleteCareerHandbook.bind(adminController));
router.patch("/candidate/update-status/:candidate_id", adminController.updateStatusCandidate.bind(adminController));
router.patch("/job/update-status/:job_id", adminController.updateStatusJob.bind(adminController));
router.patch("/company/update-business-license-status/:license_id", adminController.updateBusinessLicenseStatus.bind(adminController));
// router.patch("/company/update-status/:companyId", adminController.updateCompanyStatus.bind(adminController));
router.get("/candidate/count-all", adminController.countAllCandidates.bind(adminController));
router.get("/job/statistics/monthly", adminController.getJobStatisticsByMonth.bind(adminController));
router.get("/candidate/statistics", adminController.getCandidateStatistics.bind(adminController));
router.get("/candidate/status-stats", adminController.getCandidatesByStatusStats.bind(adminController));
router.get("/candidate/industry-stats", adminController.getCandidatesByIndustryStats.bind(adminController));
router.get("/recruiter/statistics", adminController.getRecruiterStatistics.bind(adminController));
router.get("/company/plan-stats", adminController.getCompaniesByPlanStats.bind(adminController));
router.get("/company/license-stats", adminController.getCompaniesByLicenseStats.bind(adminController));
router.get("/company/registration-trend", adminController.getCompanyRegistrationTrend.bind(adminController));
router.get("/job-applications/new-stats", adminController.getNewJobApplicationsStats.bind(adminController));
module.exports = router;
