const express = require('express');
const userController = require('../controllers/UserController');
const jwtMiddleware = require('../middleware/JWTMiddleware');
const router = express.Router();

router.post('/register', userController.registerUser.bind(userController));
router.post('/login', userController.login.bind(userController));
router.get('/verify-email', userController.verifyEmail.bind(userController));
router.get('/reset-password', userController.resetPassword.bind(userController));
router.post('/forget-password', userController.forgetPassword.bind(userController));
router.post('/change-password', userController.changePassword.bind(userController));
router.use(jwtMiddleware(["user", "admin"]));
router.get('/current-user', userController.getCurrentUser.bind(userController));
router.patch('/current-user', userController.updateUser.bind(userController));
router.get('/check-balance', userController.checkBalance.bind(userController));
router.get('/logout', userController.logout.bind(userController));
router.patch('/update-password', userController.updatePassword.bind(userController));
router.get("/conversation/all", userController.getAllConversations.bind(userController));
router.get("/conversation/most-recent", userController.getMostRecentConversations.bind(userController));
router.get("/conversation-detail/:id", userController.getConversationDetail.bind(userController));
router.get("/usage-history", userController.getUsageHistory.bind(userController));
router.get("/candidate-profile", userController.getAllCandidateProfile.bind(userController));
router.get("/candidate-profile/:id", userController.getCandidateProfile.bind(userController));
router.get("/categories-post", userController.getAllCategoriesPost.bind(userController));
router.get("/career-handbook", userController.getAllCareerHandbook.bind(userController));
router.get("/career-handbook/featured", userController.getAllFeaturedCareerHandbook.bind(userController));
router.get("/jobs", userController.getAllJobs.bind(userController));
router.get("/top-company", userController.getAllTopCompany.bind(userController));
router.get("/saved-jobs", userController.getAllSavedJobsByUser.bind(userController));
router.get("/applied-jobs", userController.getAllAppliedJobsByUser.bind(userController));
router.get("/viewed-jobs", userController.getAllViewedJobsByUser.bind(userController));
router.get("/cv-templates", userController.getAllCvTemplates.bind(userController));
router.get("/template-fields/:template_id", userController.getAllTemplateFieldsByTemplateId.bind(userController));
router.get("/user-cvs", userController.getAllUserCvByUserId.bind(userController));
router.get("/candidate-cvs", userController.getAllCandidateCvByUserId.bind(userController));
router.get("/suitable-jobs", userController.getAllSuitableJobsByUser.bind(userController));
router.get("/job-detail/:job_id", userController.getJobDetailByJobId.bind(userController));
router.get("/companies", userController.getAllCompany.bind(userController));
router.get("/company-detail/:company_id", userController.getCompanyDetailByCompanyId.bind(userController));
router.get("/career-handbook/:category_id", userController.getCareerHandbookByCategoryId.bind(userController));
module.exports = router;
